### ISSUE TITLE
Prepare test JDI demonstration project

### ISSUE THREAD

**Issue by wsbaser** [websyncio/websync-idea#6]
We need a project that we can use for testing.
It should be located in the same repository as plugin.
**We should also take into account that in future we will support other frameworks. This should be reflected in our project structure.**

1. Create folder supported-frameworks/JDI in root repository folder
2. Create page object to verify common elements initialization with locator attributes (UI,Css,XPath, etc.). It should contain JDI elements initialized with different locator attributes. And also should contain edge cases when element is initialized incorrectly - does not have locator attribute, has several locator attributes, etc.
3. Create page object to verify complex elements initialization(JTable, JMenu, etc). It should contain complex JDI elements with all supported initialization types. And also should contain edge cases when element initialized incorrectly (find out which ones).
4. Create page object to verify all supported JDI elements(existing in JDI codebase). It should contain all supported JDI elements, both common and complex.
5. Create set of classes to verify support of inherited page objects. This set should contain base page object with some JDI elements and inherited page object with some JDI elements.
6. Create set of classes to verify support of inherited components. This set should contain base component inherited with some JDI elements, inherited component with some JDI elements, couple of page objects containing inherited component.
7. Create set of classes to verify JDI page objects initialization. It should contain class inherited from WebPage, class inherited from WebPage and annotated with attribute Url. This classes should have JDI elements defined as fields with different modificators (public, private, static, etc).
8. Create set of classes to verify JDI sites. It should contain class with attribute JSite and page objects defined as fields with different modificators(public, private, static). It should contain class with attribute JSite, annotated with attribute Url and containing page objects, already annotated with attribute Url. It should contain class with attribute JSite and containing page objects already defined in other classes with attribute JSite.

Который будет содержать все возможности JDI Light которые мы будем поддерживать.
Все атрибуты, все классы, наследуемые классы, наследуемые компоненты.
Все возможные веб элементы и все возможные инициализации веб элементов (пока ограничиваемся HTML5 элементами)
Мы будем использовать этот проект для отладки проекта и будем использовать его для тестов.

Для начала - сделать тестовый проект с ОДНИМ элементом (пусть это будет ТекстБокс) и представить его на ревью Алексею
Пусть сперва будет пэйдж обжект на котором будет проверены все атрибуты локаторов, женерик атрибуты которые могут применятся ко всем локаторам. 
Навесить на элемент разрые атрибуты

**Comment by AlexeyGirin** [comment]
Closed since decomposed
